project_name: bitsongd

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
  - id: "bitsongd"
    main: ./cmd/bitsongd/main.go
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=go-bitsong -X github.com/cosmos/cosmos-sdk/version.AppName=bitsongd -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: SHA256SUMS-v{{.Version}}.txt
  algorithm: sha256

release:
  name_template: "BitSong v{{.Version}}"

archives:
  - format: binary
  - name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  - files:
    - none*