name: Compile bitsong

# Controls when the action will run.
#  This workflow runr on pushes to master & every Pull Requests. (Or when manually triggered)
on:
  push:
    #branches:
    #  - "fixs"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-test" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - run: echo "# Release notes" > ../release_notes.md
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --skip-validate   # skip validate skips initial sanity checks in order to be able to fully run

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist --release-notes=../release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}